services:
  - type: web
    name: leaflet-redis-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-map

  - type: redis
    name: redis-map
    plan: free